name: expense_repository
description: Dart package which manages the expense domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.0
  # import 'package:path/path.dart';
  # import 'package:sqflite/sqflite.dart';
  sqflite:
  path:

  #flutter pub run build_runner build
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable: